[workspace]
members = ["crates/*"]

[package]
name = "the-man"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
base64 = "0.22.1"
bincode = {version = "2", features = ["serde"]}
bytes = { version = "1.10.0", features = ["serde"] }
chrono = { version = "0.4.39", features = ["serde"] }
ciborium = "0.2.2"
cpal = "0.15.3"
ed25519 = { version = "2.2.3", features = ["serde", "serde_bytes"] }
futures-util = "0.3.31"
iroh = "0.33"
iroh-blobs = { version = "0.33", features = ["rpc"] }
iroh-gossip = { version = "0.33", features = ["rpc"] }
media-man = { path = "crates/media-man", features = ["codec-opus"] }
rand = "0.8"
serde = { version = "1.0.217", features = ["derive"] }
thiserror = "2.0.11"
tokio = { version = "1.44.0", features = ["bytes", "fs", "io-std", "io-util", "macros", "net", "rt-multi-thread", "signal", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
eframe = {version = "0.31" }
anyhow = "1"
blake3 = { version = "1.6", features = ["serde"] }
egui_tiles = "0.12.0"
